version: '3'
services:
  k8s-ver:
    image: sbh69/k8s-ver-demo:latest
    container_name: sbh69/k8s-ver-demo:latest
    hostname: k8s-ver
    networks:
      - esx
    ports:
      - 30001:8080

networks:
  esx: {}