name: publish docker image to github

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: dockerhub login
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
    - name: build docker image
      run: |
        make docker
    - name: docker hub push
      run: |
        docker push $DOCKERHUB_USER/k8s_ver_demo:latest
