name: publish docker image to github

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: set env
      run: echo "VERSION=$(grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' configuration.py)" >> $GITHUB_ENV
    - name: dockerhub login
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
    - name: build docker image
      run: |
        echo current version is: ${{ env.VERSION }}
        docker build --rm -t ${{ secrets.DOCKERHUB_USERNAME }}/k8s_ver_demo:latest -t ${{ secrets.DOCKERHUB_USERNAME }}/k8s_ver_demo:${{ env.VERSION }} .
    - name: docker hub push
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/k8s_ver_demo --all-tags
